# Generated by Django 3.2.21 on 2023-09-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_kicad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcategory',
            name='default_footprint',
            field=models.CharField(blank=True, help_text='Default footprint for this category, if not specified for an individual part', max_length=200, verbose_name='Default Footprint'),
        ),
        migrations.AddField(
            model_name='selectedcategory',
            name='default_symbol',
            field=models.CharField(blank=True, help_text='Default symbol for this category, if not specified for an individual part', max_length=200, verbose_name='Default Symbol'),
        ),
    ]
