# Generated by Django 3.2.21 on 2023-09-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_kicad', '0002_auto_20230920_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcategory',
            name='default_reference',
            field=models.CharField(blank=True, help_text='Default reference for this category, if not specified for an individual part', max_length=20, verbose_name='Default Reference'),
        ),
    ]
