# Generated by Django 3.2.22 on 2023-11-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_kicad', '0005_selectedcategory_default_value_parameter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcategory',
            name='footprint_parameter_mapping',
            field=models.JSONField(blank=True, help_text='Mapping from footprint parameter values to actual KiCad footprint names', null=True, verbose_name='Footprint Parameter Mapping'),
        ),
        migrations.AddField(
            model_name='selectedcategory',
            name='footprint_parameter_template',
            field=models.ForeignKey(blank=True, help_text='Footprint parameter template for this category, will use KICAD_FOOTPRINT_PARAMETER setting if not set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footprint_kicad_categories', to='part.partparametertemplate', verbose_name='Footprint Parameter Template'),
        ),
    ]
