# Generated by Django 3.2.23 on 2023-12-14 03:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_kicad', '0005_selectedcategory_default_value_parameter_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0, help_text='current progress', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('file_name', models.CharField(default='', help_text='Name of currently processed file.', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_progress_bar_users', to=settings.AUTH_USER_MODEL, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Progress Indicator',
                'verbose_name_plural': 'Progress Indicators',
            },
        ),
    ]
